"""
Datos de referencia: carreras reales, descargadas de Wikidata.

GENERADO AUTOMATICAMENTE por scripts/descargar_verdad.py. No editar a mano:
los cambios se pierden en la siguiente descarga.

Fuente: Wikidata, propiedades P54 (miembro de equipo deportivo) y P6087
(entrenador de equipo deportivo). Datos estructurados y curados por
personas, no prosa interpretada por un modelo.

Esto es lo que hace que evaluate.py signifique algo: comparar la extraccion
del LLM contra una referencia independiente y citable, en lugar de contra
el recuerdo de alguien.
"""

ENTRENO_A = {
    "Rinus Michels": [
        "Ajax de Ámsterdam",
        "Bayer 04 Leverkusen",
        "F. C. Colonia",
        "Fútbol Club Barcelona",
        "Los Angeles Aztecs",
        "Selección de fútbol de los Países Bajos",
    ],
    "Johan Cruyff": [
        "Ajax de Ámsterdam",
        "Fútbol Club Barcelona",
        "Selección de fútbol de Cataluña",
    ],
    "Louis van Gaal": [
        "AZ Alkmaar",
        "Ajax de Ámsterdam",
        "F. C. Bayern Múnich",
        "Fútbol Club Barcelona",
        "Manchester United Football Club",
        "Selección de fútbol de los Países Bajos",
        "selección de fútbol sub-19 de los Países Bajos",
    ],
    "Arrigo Sacchi": [
        "A.C. Milan",
        "Atlético de Madrid",
        "Parma Calcio 1913",
        "Rimini FC",
        "Selección de fútbol de Italia",
    ],
    "Marcelo Bielsa": [
        "Athletic Club",
        "Club Atlas de Guadalajara",
        "Club Atlético Newell’s Old Boys",
        "Club Atlético Vélez Sarsfield",
        "Club de Fútbol América",
        "Leeds United Association Football Club",
        "Lille Olympique Sporting Club",
        "Olympique de Marsella",
        "Real Club Deportivo Espanyol de Barcelona",
        "Selección Chilena de Fútbol",
        "Selección de fútbol de Uruguay",
        "selección de fútbol de Argentina",
    ],
    "Pep Guardiola": [
        "F. C. Bayern Múnich",
        "Fútbol Club Barcelona",
        "Fútbol Club Barcelona Atlètic",
        "Italy",
        "Manchester City Football Club",
    ],
    "José Mourinho": [
        "A.S. Roma",
        "Chelsea Football Club",
        "Fenerbahçe Spor Kulübü",
        "Fútbol Club Oporto",
        "Inter de Milán",
        "Manchester United Football Club",
        "Real Madrid Club de Fútbol",
        "Sport Lisboa e Benfica",
        "Tottenham Hotspur Football Club",
        "União Desportiva de Leiria",
    ],
    "Carlo Ancelotti": [
        "A.C. Milan",
        "Associazione Calcio Reggiana 1919",
        "Chelsea Football Club",
        "Everton F.C.",
        "F. C. Bayern Múnich",
        "Juventus",
        "Paris Saint-Germain FC",
        "Parma Calcio 1913",
        "Real Madrid Club de Fútbol",
        "Selección de fútbol de Brasil",
        "Società Sportiva Calcio Napoli",
    ],
    "Mauricio Pochettino": [
        "Chelsea Football Club",
        "Paris Saint-Germain FC",
        "Real Club Deportivo Espanyol de Barcelona",
        "Selección de fútbol de los Estados Unidos",
        "Southampton Football Club",
        "Tottenham Hotspur Football Club",
    ],
    "Diego Simeone": [
        "Atlético de Madrid",
        "Catania Football Club",
        "Club Atlético River Plate",
        "Club Atlético San Lorenzo de Almagro",
        "Club Estudiantes de La Plata",
        "Racing Club",
        "Società Sportiva Calcio Napoli",
    ],
    "Mikel Arteta": [
        "Arsenal Fútbol Club",
    ],
    "Jürgen Klopp": [
        "1. FSV Mainz 05",
        "Borussia Dortmund",
        "Liverpool Fútbol Club",
        "Selección de fútbol de Alemania",
    ],
    "Xavi Hernández": [
        "Al-Sadd Sports Club",
        "Fútbol Club Barcelona",
    ],
    "Roberto De Zerbi": [
        "Benevento Calcio",
        "Brighton & Hove Albion Football Club",
        "Calcio Foggia 1920",
        "FK Shajtar Donetsk",
        "Olympique de Marsella",
        "Palermo FC",
        "Tottenham Hotspur Football Club",
        "U.S. Darfo Boario S.S.D.",
        "Unione Sportiva Sassuolo Calcio",
    ],
}

JUGO_EN = {
    "Rinus Michels": [
        "Ajax de Ámsterdam",
        "Selección de fútbol de los Países Bajos",
    ],
    "Johan Cruyff": [
        "Ajax de Ámsterdam",
        "Feyenoord Rotterdam",
        "Fútbol Club Barcelona",
        "Levante Unión Deportiva",
        "Los Angeles Aztecs",
        "Selección de fútbol de Cataluña",
        "Selección de fútbol de los Países Bajos",
        "Washington Diplomats",
    ],
    "Louis van Gaal": [
        "AZ Alkmaar",
        "Ajax de Ámsterdam",
        "Royal Antwerp Football Club",
        "Sparta Rotterdam",
        "Telstar",
    ],
    "Marcelo Bielsa": [
        "Club Atlético Argentino",
        "Club Atlético Newell’s Old Boys",
        "Instituto Atlético Central Córdoba",
    ],
    "Pep Guardiola": [
        "A.S. Roma",
        "Al-Ahli SC Doha",
        "Brescia Calcio",
        "Dorados de Sinaloa",
        "Fútbol Club Barcelona",
        "Fútbol Club Barcelona Atlètic",
        "Selección de fútbol de Cataluña",
        "Selección de fútbol sub-21 de España",
        "selección de fútbol de España",
        "selección de fútbol sub-23 de España",
    ],
    "José Mourinho": [
        "Clube de Futebol Os Belenenses",
        "G.D. Sesimbra",
        "Rio Ave Futebol Clube",
        "União Futebol Comércio e Indústria",
    ],
    "Carlo Ancelotti": [
        "A.C. Milan",
        "A.S. Roma",
        "Parma Calcio 1913",
        "Selección de fútbol de Italia",
        "selección de fútbol sub-21 de Italia",
    ],
    "Mauricio Pochettino": [
        "Club Atlético Newell’s Old Boys",
        "FC Girondins de Burdeos",
        "Paris Saint-Germain FC",
        "Real Club Deportivo Espanyol de Barcelona",
        "Selección de fútbol sub-23 de Argentina",
        "selección de fútbol de Argentina",
        "selección de fútbol sub-20 de Argentina",
    ],
    "Diego Simeone": [
        "Atlético de Madrid",
        "Club Atlético Vélez Sarsfield",
        "Inter de Milán",
        "Pisa Sporting Club",
        "Racing Club",
        "Selección de fútbol sub-23 de Argentina",
        "Sevilla Fútbol Club",
        "Società Sportiva Lazio",
        "selección de fútbol de Argentina",
        "selección de fútbol sub-20 de Argentina",
    ],
    "Mikel Arteta": [
        "Antiguoko",
        "Arsenal Fútbol Club",
        "Everton F.C.",
        "Fútbol Club Barcelona",
        "Fútbol Club Barcelona \"C\"",
        "Fútbol Club Barcelona Atlètic",
        "Paris Saint-Germain FC",
        "Rangers Football Club",
        "Real Sociedad de Fútbol",
        "Selección de fútbol sub-21 de España",
        "selección de fútbol sub-16 de España",
        "selección de fútbol sub-17 de España",
        "selección de fútbol sub-18 de España",
    ],
    "Jürgen Klopp": [
        "1. FC Pforzheim",
        "1. FSV Mainz 05",
        "Eintracht Frankfurt",
        "Eintracht Frankfurt II",
        "Rot-Weiss Frankfurt",
    ],
    "Xavi Hernández": [
        "Al-Sadd Sports Club",
        "Fútbol Club Barcelona",
        "Fútbol Club Barcelona Atlètic",
        "Selección de fútbol de Cataluña",
        "Selección de fútbol sub-21 de España",
        "selección de fútbol de España",
        "selección de fútbol sub-17 de España",
        "selección de fútbol sub-18 de España",
        "selección de fútbol sub-20 de España",
        "selección de fútbol sub-23 de España",
    ],
    "Roberto De Zerbi": [
        "A.C. Milan",
        "A.C. Monza",
        "Brescia Calcio",
        "CFR Cluj",
        "Calcio Como 1907",
        "Calcio Foggia 1920",
        "Calcio Lecco 1912",
        "Calcio Padova",
        "Catania Football Club",
        "S.S. Arezzo",
        "Società Sportiva Calcio Napoli",
        "Trento Calcio 1921",
        "Unione Sportiva Avellino",
        "selección de fútbol sub-20 de Italia",
    ],
}
